export const ADVENTURE_STORIES: string[] = [
  "You help an elderly herbalist carry her heavy baskets across a muddy road.",
  "You stop at the local tavern, sipping ale while listening to mercenaries brag about their hunts.",
  "A small kid in the village runs up and asks if you've ever slain a real dragon.",
  "You find a lost puppy shivering in a hollow tree and guide it back to the village gate.",
  "A traveling bard plays a lively tune, prompting travelers to dance around the campfire.",
  "You help a merchant push his carriage wheel out of a deep mud pit.",
  "A mysterious hooded figure whispers a rumor about hidden ruins before slipping into the shadows.",
  "You stop by a crystal-clear spring to replenish your water flask and rest your feet.",
  "An old knight sitting on a bench shows you a scar from a battle with an Ancient Golem.",
  "You help a farmer search for a stubborn sheep that wandered into the brambles.",
  "A wild squirrel throws an acorn at your head from a tall oak branch. Cheeky creature!",
  "You find a hollow log containing a child's hand-carved wooden sword.",
  "A flock of startled birds suddenly takes flight, warning you to watch your surroundings.",
  "You notice a circle of glowing mushrooms and decide to walk carefully around them.",
  "The delicious aroma of roasting meat draws you near a hunter's campsite.",
  "You spend a few minutes helping an alchemist sort wild herbs by color.",
  "A stray cat rubs against your boots, demands quick scratches, then walks away.",
  "You read a faded bounty poster on a wooden notice board, warning of goblin raiders.",
  "A cool breeze carries the distant, haunting sound of a flute from deep in the woods.",
  "You tighten your boot laces and double-check your weapon sheaths before marching on.",
  "A friendly traveler passes you on the road and offers you a handful of sweet berries.",
  "You notice a peculiar symbol carved into a mossy boulder along the path.",
  "A butterfly lands on your knuckle, sitting quietly before fluttering away.",
  "You help a blacksmith's apprentice carry bundles of charcoal to the forge.",
  "You sit on a fallen log to write a short entry in your exploration journal.",
  "A sudden downpour forces you to seek shelter under a thick canopy of pine trees.",
  "You hear a loud roar echoing from the mountain peaks and look up warily.",
  "You find a discarded copper coin half-buried in the dirt and polish it clean.",
  "An old woman gives you a freshly baked loaf of bread in exchange for chopping firewood.",
  "You watch a hawk dive gracefully from the clouds, catching a mouse in the grass.",
  "A group of village children challenge you to a game of hide and seek.",
  "You discover an old stone well and throw a coin in for good luck.",
  "A talkative merchant tells you about the rare minerals hidden deep in the Scorched Wastes.",
  "You help a young girl retrieve her lost kite from the lower branches of a willow tree.",
  "You stop to watch a team of busy ants carry a giant leaf back to their nest.",
  "A warm, golden light breaks through the tree branches, lifting your spirits.",
  "You find a horseshoe nailed to a fence post—a traditional sign of good luck.",
  "You listen to a priest reciting ancient legends outside a small stone shrine.",
  "A deer crosses your path, pausing to stare at you before leaping into the brush.",
  "You help clean up spilled apples after a merchant's cart bumps over a stone.",
  "You share some of your rations with a hungry beggar sitting by the road.",
  "You find a weathered signpost pointing towards the Whispering Caves.",
  "A local fisherman shows off a massive catfish he caught in the nearby river.",
  "You pause to inspect a patch of blue flowers, noting their sweet scent.",
  "A gust of wind blows your hat off, sending you on a short chase down the trail.",
  "You sit by a babbling brook, watching small silver fish swim against the current.",
  "You find a cracked leather pouch containing nothing but dry sand and a small pebble.",
  "A villager asks for help searching the cellar for a missing wedding ring.",
  "You watch a colorful butterfly battle against a gentle autumn breeze.",
  "An apprentice mage accidentally fires a spark into a hay bale; you help stomp it out.",
  "You find a rusted iron key in the dirt and pocket it, wondering what it unlocks.",
  "A friendly woodsman shows you a shortcut through the denser parts of the forest.",
  "You help an old man gather wild mushrooms, making sure to avoid the poisonous ones.",
  "You spend a moment looking at the clouds, identifying shapes of swords and shields.",
  "A traveler shares a story of a mythical phoenix that nests in the Scorched Wastes.",
  "You find a patch of wild wild berries and enjoy a sweet afternoon snack.",
  "A young boy asks if he can polish your shield to make it look like a mirror.",
  "You discover a small wooden shrine dedicated to the goddess of harvests.",
  "You help an alchemist gather clean morning dew from large fern leaves.",
  "A majestic owl watches you from a high tree hollow as dusk begins to fall.",
  "You find a silver button shaped like a leaf, likely lost by a wealthy traveler.",
  "You help a farmer fix a broken wooden fence to keep the cows from escaping.",
  "A tavern maid tells you a ghost story about the Cursed Graveyard.",
  "You watch a swarm of fireflies dance over a marshy meadow as twilight sets in.",
  "A friendly miner shows you how to identify gold veins in raw stone.",
  "You help pull a stubborn mule back onto the main road.",
  "A traveling scholar asks if you've seen any ancient runes during your travels.",
  "You find a wooden toy knight carved with surprising detail in the grass.",
  "A gentle morning mist blankets the trail, making the world feel quiet and still.",
  "You help a village baker stack heavy sacks of flour near the ovens.",
  "A chipmunk scampers onto your boot, sniffs your laces, and runs off.",
  "You discover a hidden cave entrance, but decide it's too dark to explore today.",
  "You stop to help an artist retrieve a charcoal pencil that rolled down a hill.",
  "A merchant offers you a discount on a shiny copper ring, but you pass.",
  "You watch a spider spin an intricate web between two wild rose bushes.",
  "You find a small bottle of perfume that still smells faintly of lavender.",
  "You help a shepherd count his flock before the sun sets.",
  "A child hands you a shiny round river pebble as a token of friendship.",
  "You listen to the rhythmic clanging of the village blacksmith at work.",
  "You find a scrap of parchment with a half-finished drawing of a castle.",
  "A friendly hunter warns you about wolf packs roaming the northern ridges.",
  "You help a tavern keeper sweep the front porch after a busy night.",
  "A gentle autumn leaf falls directly into your open palm.",
  "You discover a stone marker commemorating a legendary battle fought long ago.",
  "You help a young boy find his lost wooden marble in the tall weeds.",
  "A traveling peddler tries to sell you some 'magical' soap.",
  "You stop to watch a group of frogs singing on lily pads in a quiet pond.",
  "You find a lost leather glove and hang it on a branch so the owner can find it.",
  "You help a herbalist dry wild chamomile flowers on wooden screens.",
  "A sudden gust of wind shakes a shower of golden leaves from the trees.",
  "You watch a fox jump mouse-hunting in a tall grassy field.",
  "You discover a patch of wild mint and chew a leaf for a refreshing taste.",
  "You help a merchant tie down his canvas cover before a storm hits.",
  "A local guard tells you about a mysterious cave hidden behind a waterfall.",
  "You find a discarded wooden carving of a small bear cub.",
  "You sit by a campfire, enjoying the warmth as night begins to chill the air.",
  "A friendly farmer offers you a cup of fresh apple cider.",
  "You watch a turtle slowly make its way across the gravel path.",
  "You help a child retrieve a ball that rolled under a thorny rose bush.",
  "You notice the first stars of the evening appearing in the darkening sky."
];
